# This is the default config file. It's versioned, so don't edit it directly.
# To edit the configuration, make one or both of the following files:
# - development.yaml
# - production.yaml
# Values in these files override the defaults.

port: 8484 # if using HTTPS, the port is ignored and 443 is used instead
https:
  use: false
  key:
  certificate: